augment: true
aw_param: 1.7
batch_size: 512
data_dir: /mnt/8T/home/estar/data/DanceTrack/trackers_gt_GSI
det_dir: datasets/MOT17/train
device: cuda
diffnet: HMINet
encoder_dim: 256
epochs: 800
eps: 0.001
eval_at: 800
eval_device: None
eval_every: 20
eval_expname: mot_ddm_1000_deeper
eval_mode: true
gpus:
- 0
high_thres: 0.6
info_dir: datasets/MOT17/train
interval: 5
low_thres: 0.1
lr: 0.0001
model_path: pretrained/motion/MOT_epoch800.pt
preprocess_workers: 16
reid_dir: pretrained/reid
save_dir: outputs/mot17
seed: 123
tf_layer: 3
w_assoc_emb: 2.2
